image: node:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_TAG =~ /v\.\d+\.\d+\.\d+\-?.*/
      changes:
        - src/package.json

stages:
  - test
  - deploy

testing:
  stage: test
  script:
    - cd src
    - npm install
    - npm run test

deploy:
  stage: deploy
  script:
    # Must get packages from npmjs.org using standard CA
    - cd src
    - npm install

    # Note: that it seems only tls.crt and tls.key are available in build-image
    - npm config set cafile /mnt/certs/tls.crt
    - npm run build
    - echo "@opensource:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" >> .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish